### ISSUE TITLE
Background Option NEW!

### ISSUE THREAD

**Issue by Deviantkool** [evertiro/historical-redux2#130]
Ok first there is Upload option; a Color option. Now what i would like you to do is add these options in an array. Eg. array( 'upload' => '', 'color' => '', 'select' => 'background-repeat_values', 'select' => 'background-position_values'). Now that is a plus to benefit all of us. GREAT JOB along with my new input. LETS BUILD WordPress.

**Comment by evertiro** [comment]
Background option could be useful... I've always done it manually as separate options. I'll think about adding it officially!

**Comment by cyberwani** [comment]
It will be a nice option.

**Comment by fierceangel** [comment]
Agreed, I like the feature in SMOF Options, would be great to see it in Redux.

**Comment by dovy** [comment]
@fierceangel That's an option in SMOF? I don't think so... Unless someone just added it brand new.

The only issue is you can do SO many variations with background.

Scroll/Fixed, Stretch, Tile, Center, BG Color, RGB, Transitioning, etc.

To try and make one module would be... Intensive. I think it's easier to keep it up to the developer how they want to implement. Can you give me an an argument otherwise?

**Comment by dovy** [comment]
@Deviantkool

**Comment by Deviantkool** [comment]
Yes you are right i solved my background issues a long time ago. Plus the framework has all the fields needed to create this option. I did without modifying any of the fields. Great work you guys.
