### ISSUE TITLE
Dynamically Generate CSS File

### ISSUE THREAD

**Issue by teamcrisis** [evertiro/historical-redux2#152]
@dovy, could you please build something like the following into Redux, or at least add some hooks into Save/Reset so a user could add this feature themselves without messing with the core?

http://aquagraphite.com/2011/11/dynamically-generate-static-css-files-using-php/

**Comment by dovy** [comment]
This can be achieved in 2 ways with 3.0

The first occurs on every save. There's a hook called `do_action( 'redux-saved-' . $this->args['opt_name'] , $value );`. To use this you would need to know your `opt_name` obviously. This would be something you could hook to each and every page load.

Say your body background and font color are things you want to recompile in a css file. You would then hook to the above action, like so:

``` php
<?
function genCss($options) {
 // GENERATE CSS HERE, $options is the last saved options array
}
add_action( 'redux-saved-teamcrisis', 'genCss' );
// This assumes your opt_name is called teamcrisis
```

Now the much more elegant way is to set a compiler=>true flag for each item that would trigger a new compile. Otherwise you're recompiling every page load. BAD.

If that's the case you'd do the same thing as above, but change the hook.

``` php
<?
function genCss($options) {
 // GENERATE CSS HERE, $options is the last saved options array
}
add_action( 'redux-compiler-teamcrisis', 'genCss' );
// This assumes your opt_name is called teamcrisis
```

This only runs if you change a item that is set with compiler=>true as an attribute. If something without a compiler attribute is saved, that hook never happens.

How about that?  ;)

**Comment by teamcrisis** [comment]
@dovy thanks for getting back to me. Just so I can wrap my head around this, would I be doing something like this?

```
function genCss($options) {

    $css_dir = get_stylesheet_directory() . '/css/'; // Shorten code, save 1 call
    ob_start(); // Capture all output (output buffering)

    require($css_dir . 'styles.php'); // Generate CSS

    $css = ob_get_clean(); // Get generated CSS (output buffering)
    file_put_contents($css_dir . 'options.css', $css, LOCK_EX); // Save it
}
```

And set `compiler=>true` to any option I make use of in the `styles.php` file?

**Comment by dovy** [comment]
@teamcrisis Let me give you the proper way to do it.

Let's say you a css file that your theme includes (enqueues). You should have previously registered and enqued it.

Now say you have some dynamic CSS you want to add to that files because your options panel is that functional. ;)   You could use a function like this and be sure that your CSS is loading properly without generating a new file.

``` php
<?php
function background_css( ) {
  global $options;
  $bg_color = $options['color_body_bg'];
  $color = '#' . str_replace( '#', '', $bg_color ) . ';';
  $theCSS = 'body { background-color: ' . $color . '; }';
  wp_add_inline_style( 'theme_css', $theCSS );
}
add_action( 'wp_enqueue_scripts', 'background_css' );
```

Let's look at this code. I am able to create CSS dynamically this way. My previously enqueued theme CSS was registered with the name theme_css. The above function generates some new CSS, and appends whatever I pass to that previously enqueued file.

You can do this a number of times to the same file. This is just clean coding and doesn't require the file_put_contents (which ThemeForest looks down on. You'd have to use the $wp filesystem instead.

The other methods I spoke of were if you had a LESS or SASS compiler. It sounds like, to me, you just want to update colors and such depending on the values in your options panel. This example should get you to where you need to go.  ;)

**Comment by teamcrisis** [comment]
@dovy, thanks for getting back to me with more information. To be honest, I don't see the advantage of your example. It just seems overly complicated with little benefit. 

What I currently do is this:

```
background-color: <?php echo $smof_data['bg_color']; ?>;
```

It's one line of code. Clean, simple and straightforward. When the user picks a new color and clicks the save button, SMOF simply updates the value and regenerates the css file which I then enqueue. 

What would I do when I need to test for conditions before css is added to the file? Right now I do this:

```
<?php if (!empty($smof_data['logo'])) : ?>
    .logo { 
        background-image: url('<?php echo $smof_data['logo']; ?>');
        background-repeat: no-repeat;
        height: <?php echo $smof_data['logo_height']; ?>;
        width: <?php echo $smof_data['logo_width']; ?>;
    }
<?php endif; ?>
```

Again, very simple and straightforward.

Maybe I'm completely misunderstanding the simplicity of what you're trying to show me, but at this point it just seems far more complicated with no benefit over what I currently do. 

Does anyone else in the community have any input on this? Personally, I prefer the way I do it with SMOF. It just seems less error prone and easier to debug, since to me, it's more clean and simple.

**Comment by teamcrisis** [comment]
The only advantage I can see with your example is it's one less css file to be registered and enqueued, since you're appending the generated css to an already enqueued css file. 

However, most sites that take advantage of various plugins should really be using some type of cache/minify plugin to combine like files. So I'm still not entirely convinced your example is the better way of doing it.  

I still feel the simplicity of my example outweighs the advantage of one less request in the head - especially when a decent caching plugin can take care of the issue relatively easily.

**Comment by dovy** [comment]
@teamcrisis The reason it seems complicated is you're thinking as a web dev and no a Wordpress dev. Let me explain. The main reason to do things like enqueue and such is that's what ThemeForest and others marketplaces want/demand, and it doesn't break plugins and features like page caching such as the excellent W3 plugin.

So let's make the previous example match your code:

``` php
<?php
function background_css( ) {
  global $options;
  $theCss = 'body {background-color: '.$options['bg_color'].';}';
  if (!empty($smof_data['logo'])) :
  $theCSS .= '.logo { ';
   $theCSS .= 'background-image: url("'.$options['logo'].'");'
   $theCSS .= 'background-repeat: no-repeat;'
   $theCSS .= 'height: '.$options['logo_height'].';'
   $theCSS .= 'width: '.$options['logo_width'].';'
  $theCSS .= '{';
  wp_add_inline_style( 'theme_css', $theCSS );
}
add_action( 'wp_enqueue_scripts', 'background_css' );
```

This dynamically generates a pretty string that's minimised and appended to your theme's CSS file if it was properly enqueued as `theme_css`.

Now don't get me wrong, I'm all for using the compiler method. If you go that route, you need to use the proper Wordpress file API instead of file_put_contents (demands on ThemeForest yet again). ThemeForest doesn't require these methods to be mean. The Wordpress File API has a bunch of functions that works on more than linux boxes. I believe there are a few web servers that file_put_contents doesn't work as expected. The file API takes this and other things like permissions into account. That's why we use Wordpress, because it's well rounded. We shouldn't try to bypass the code there, when we have very useful built-in functions. Here's an example on how to do it this way with the compiler hook:

``` php
function genCss($options) {

    global $wp_filesystem;
    // Initialise the Wordpress filesystem, no more using file_put_contents function
    if (empty($wp_filesystem)) {
        require_once(ABSPATH .'/wp-admin/includes/file.php');
        WP_Filesystem();
    }  

    $css_dir = get_stylesheet_directory() . '/css/'; // Shorten code, save 1 call
    ob_start(); // Capture all output (output buffering)

    ?>
        body {
            background-color: <?php echo $options['bg_color']; ?>;
        }
        <?php if (!empty($options['logo'])) : ?>
        .logo { 
            background-image: url('<?php echo $options['logo']; ?>');
            background-repeat: no-repeat;
            height: <?php echo $options['logo_height']; ?>;
            width: <?php echo $options['logo_width']; ?>;
        }
        <?php endif; ?>    
    <?php

    $css = ob_get_clean(); // Get generated CSS (output buffering)
    $wp_filesystem->put_contents(
      $css_dir . 'options.css',
      $css,
      FS_CHMOD_FILE // predefined mode settings for WP files
    );    
}
add_action( 'redux-compiler-teamcrisis', 'genCss' );

function styleCSS() {
    wp_enqueue_style(
        'themecrisis-THISTHEME-generated-css', 
        get_stylesheet_directory() . '/css/options.css', 
        time(),
        true
    );      
}
add_function('wp_head', 'styleCSS');
```

One word of caution, I don't like using `ob_start` as much because my CSS file isn't minimised. It has all the indentations I used to make the code easier to read. If you mess with PHP strings instead, you can indent in the PHP and only indent in the string. You do, of course, have to code in a more PHP way than a CSS way.

Either of the above examples will get you where you need to go. Just make sure you enqueue and use the wp file API any time you're writing files.

**Comment by dovy** [comment]
@teamcrisis That's fine, just make sure you enqueue as well as use the Wordpress file system.

http://ottopress.com/2011/tutorial-using-the-wp_filesystem/

That's why I included both examples.  ;)

**Comment by teamcrisis** [comment]
@dovy, thank you for taking the time to give me further input, it's greatly appreciated!

I guess my client-sided brain just likes your second example better for some reason. I'll attempt to give both options a try when v3 is released and go with what I can wrap my head around.

Thanks again for your time and contribution.

**Comment by dovy** [comment]
@teamcrisis You're welcome. You can do it your way. I only tell you what would give your users the best experience.

Either way, the new Redux will do all you need, want, and even more.   Heh.
