### ISSUE TITLE
Stil having problems with more than two instances of the main class

### ISSUE THREAD

**Issue by DietmarHartje** [evertiro/historical-redux2#2]
Creating two instances of the admin class will cause the first instance to be overwritten... Is there any plan to change this? Would be great if you use more than one plugin with your wordpress installation.

**Comment by evertiro** [comment]
The problem is that you can't have more than one identically named class... I plan on putting up instructions on how to modify it, but the short version is edit admin/options/options.php and rename the class. If you're running on a linux based server, you can rename the class (and all entities using 'Redux' in the name) by running "for i in $(grep -R 'Redux' | cut -d ':' -f 1); do sed -i 's|Redux|<your plugin>|g' $i; done;"

**Comment by DietmarHartje** [comment]
Thanx for the reply. As far as I can see the problem is that you may should wrap all array about input fields and the settings of the settings page itself into one bigger array...
