### ISSUE TITLE
adding post metaboxes

### ISSUE THREAD

**Issue by htrex** [evertiro/historical-redux2#24]
this framework seems great, what about using it to add custom post metaboxes too?
that would be awesome! :)

**Comment by hamed-alshukri** [comment]
+1

**Comment by bimaljr** [comment]
+1

**Comment by evertiro** [comment]
How would you envision that working?

**Comment by kwayyinfotech** [comment]
I will try some possibilities and let's see if it will be usable or not

**Comment by htrex** [comment]
https://github.com/rilwis/meta-box this works quite well but is for metaboxes only

**Comment by Pushplaybang** [comment]
https://github.com/Gizburdt/Wordpress-Cuztom-Helper  is pretty awesome, doing more than just metaboxes, seems really nice, but doesn't have the same range of fields that REDUX might. If it only its was as simple as smashing two cakes together.  but alas, its not.

I also think there is something to be said for specialization rather than diversification here.  I would much rather see further maturity in the options panel  over meta boxes personally.

**Comment by psaikali** [comment]
I agree with @Pushplaybang, I think the goal of this framework is to create/extend settings page, and the focus should remain this particular feature. Adding metaboxes/taxonomies/custom content types is easily doable with Cuztom Helper mentioned above. I personally use Redux coupled with Cuztom in my themes, and I'm very happy with it.

**Comment by hamed-alshukri** [comment]
You are right. There are multiple script we can use to create metaboxes but there is something you might forgot it. Using other script means if the users export their setting from Redux options panel, they will only export the options panel settings not the other setting from other script. On other hand, if the framework has metaboxes integrated into it, the users can export their settings from one place. 
At least if the metaboxes not builtin into the framework, it would great if someone release a separate script to extend the framework.

**Comment by Pushplaybang** [comment]
@UniqueCreativity.   I wholeheartedly disagree with you, metaboxes are not and should not be used for theme options at all in my opinion.  They should be relevant to the content where they appear, and so should be imported and exported with that content rather than during the theme setup.

**Comment by evertiro** [comment]
I'm leaning towards agreeing with Pushplaybang and psaikali in that Redux is designed exclusively for the options panel (hence Redux Options Framework). However, I'm not against creating a separate product that is a framework for other aspects of a theme or plugin including metaboxes...

**Comment by djevrek** [comment]
There is something like this already https://github.com/rilwis/meta-box, i'm using it on themes with combination with redux.

**Comment by htrex** [comment]
Researched a bit and found a better alternative to all the frameworks of this kind I've tried before this:
http://wordpress.org/extend/plugins/advanced-custom-fields/

It does both option panels and metaboxes, allows to visually create interfaces, extensible with your own modules in a well coded framework, export your configuration and include it in your theme or plugin together with a light runtime lib, has an extended and growing community too... it really raises the bar.

**Comment by Pushplaybang** [comment]
while ACF looks great, I'm a bigger fan of projects like redux and gizburdts cuztom helper because by breaking them down and digging in theres an opportunity to learn and improve my own skills as a developer, which really helps as I do a lot of very customized wp theming / admin development for clients. Secondly its much more rewarding for me using something I can meaningfully contribute to in the community / open source context.  

While ACF looks like a time saver and a great "premium" option  (I'm by no means knocking it), I think its just for a different audience, not necessarily "better" as you suggest.

**Comment by Pushplaybang** [comment]
@ghost1227   +1 for a redux metabox framework,  you've got the fields done here already to a large degree.

**Comment by evertiro** [comment]
Closing this for now, I might look into creating a metabox framework in the future.
