### ISSUE TITLE
Enhanced Google Webfonts

### ISSUE THREAD

**Issue by evertiro** [evertiro/historical-redux2#35]
I've been playing with directly integrating the webfonts API, but if anyone has seen a functional jQuery plugin that will do it for me, I certainly wouldn't complain! The problem with the current solution is that it doesn't query the API, but is defined by a hardcoded list. This results in missing fonts, and a notable lack of variants.

**Comment by psaikali** [comment]
![screen-2013-01-07-2 46 00 PM](https://f.cloud.github.com/assets/1606655/47816/bcdb0a82-58e9-11e2-9ca7-2c3cc572632d.png)

Hi there,

I spent my morning working on that, as I needed it.
It's still a work in progress, but it's working (almost) fine: I load the webfonts using the API (querying in PHP), and WP-transient-cache the results for 1 day. Finally, the populated select menu is enhanced with the Chosen jQuery plugin to make it easier to find a specific font.

The stored value is the font name with spaces replaced by '+', following https://developers.google.com/webfonts/docs/getting_started#Syntax

Fields files are here > http://img.saika.li/Lz1q

The unique problem I found for now is that the Chosen doesn't work well (select is empty) if you load the page options from a tab where there is no gfonts field; I think that's because the framework options.js hide the other tabs' contents first, and then my field js is executed and Chosen might not work well with hidden select. I couldn't fix it yet.

I first tried loading the fonts through the API using JS, but due to the large ammount of fonts, my browser went crazy trying to populate the select. I then thought of PHP and caching the results.

Hope it helps! I'll keep updating this post on later updates.

**Comment by evertiro** [comment]
I love where you're going with this! Definitely keep me updated!

**Comment by djevrek** [comment]
Maybe you should use github for your code (make fork) so we can all use your code easier. Maybe author of Redux can marge this (maybe even without Chosen JS) because of better and updated list of fonts (its automatic because of using API)

**Comment by psaikali** [comment]
The problem is that I haven't forked/cloned it, I just download and started
my own customization/enhancements. That's why I sent files above!

I might add some font previewing (after selection only) someday soon, I'll try to do it the good Github way next time ;)

**Comment by evertiro** [comment]
Forking is always easiest, but I'm more than willing to get my hands dirty with some unmergable code too! :) I'll be trying to integrate this shortly... Just have to finish a server migration first.

**Comment by psaikali** [comment]
Yeah, I'll fork it this week and implement the new fields/modified fields
in my repo. I'll let you know!

2013/1/8 Ghost1227 notifications@github.com

> Forking is always easiest, but I'm more than willing to get my hands dirty
> with some unmergable code too! :) I'll be trying to integrate this
> shortly... Just have to finish a server migration first.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ghost1227/Redux-Framework/issues/35#issuecomment-12002177.

## 

Pierre Saïkali
http://saika.li/
@psaikali

**Comment by evertiro** [comment]
Linking Chosen so I don't forget about it. I actually like it!

http://harvesthq.github.com/chosen/

**Comment by psaikali** [comment]
Yeah it's a great little tool. BTW I found how to fix the bug I mentioned
above about it, you have to hardcode the width of a couple of Chosen
elements in your css, otherwise it'll automatically get width:0px; if you
first load a tab that doesn't have any gfonts field.
I'll put everything in my repo anyway!

2013/1/8 Ghost1227 notifications@github.com

> Linking Chosen so I don't forget about it. I actually like it!
> 
> http://harvesthq.github.com/chosen/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ghost1227/Redux-Framework/issues/35#issuecomment-12003538.

## 

Pierre Saïkali
http://saika.li/
@psaikali

**Comment by psaikali** [comment]
BTW this new field (and some others) have been added to my forked repo > https://github.com/psaikali/Redux-Framework

**Comment by evertiro** [comment]
Closing until clean pull request is posted.
