### ISSUE TITLE
New handling of std values

### ISSUE THREAD

**Issue by denis0706** [evertiro/historical-redux2#63]
I think we can improve handling of std values.
In some cases it is needed std values to be set when updating.
If you don't want to set std in DB, just don't set std in options.php
If std is set in options.php and std_show=true - default options is just showing,
If std is set in options.php and std_show=false - default options is set.

What do you think about this?

**Comment by signo** [comment]
Could you please elaborate the scenario when you need std values saved in the db?

As of now if std_show = true when you call the get() method it will return the std value, so you will always get back the std as if it was saved in the db. To make it clearer the get() method behaves in the following way:

the field 'test' is defined as a number with a std value of 4, the following statement $var = redux->get('test', 0) will return 4 if the value is not set and a 0 if the std is not set, that is because get() looks first for the saved value, next for the std value and last for the default value passed as a parameter.

Hope this makes it clearer.

**Comment by evertiro** [comment]
I think this is handled... if not, please re-open.
