### ISSUE TITLE
Upload Type not notifying changes should be saved

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#69]
When using the upload type, after selecting or removing an image, the "Settings have changed, you should save them!" box does not appear.

**Comment by denis0706** [comment]
It happens because we change only value of 'Upload Type' input with javascript, but 'change' event isn't triggered.
But notify is shown [only when this event is triggered](https://github.com/ghost1227/Redux-Framework/blob/master/options/js/options.js#L51-L54).
So we can add `.trigger('change');` while we change some values of input fields such as 'Upload Type' :
[how it is now](https://github.com/ghost1227/Redux-Framework/blob/master/options/fields/upload/field_upload_3_4.js#L45), how it must be: `jQuery('#' + formfield).val(imgurl).trigger('change');`

Another problem i have found - event handler is bind only for inputs/selects/textareas that have been existed by the time of binding. Fox exampe changing 'Multi Text Option' field won't show notify. 
So we must use [delegated events](http://api.jquery.com/on/#direct-and-delegated-events) to solve this problem.
[How it is now](https://github.com/ghost1227/Redux-Framework/blob/master/options/js/options.js#L51). [How it should be.](https://github.com/denis0706/Redux-Framework/blob/master/options/js/options.js#L51)
